[versions]
spring-boot = "3.5.6"
errorprone = "2.42.0"

## Plugins
spring-dependency-management = "1.1.7"
gradle-git-properties = "2.5.3"
gradle-sonar = "6.3.1.5724"
gradle-errorprone = "4.3.0"
gradle-node = "7.1.0"

[libraries]
errorprone = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }

[plugins]
## Spring Boot - https://docs.spring.io/spring-boot/gradle-plugin/index.html
springBoot = { id = "org.springframework.boot", version.ref = "spring-boot" }
## Spring Dependency Management plugin - https://github.com/spring-gradle-plugins/dependency-management-plugin
springDependencyManagement = { id ="io.spring.dependency-management", version.ref = "spring-dependency-management" }

## Git properties - https://github.com/n0mer/gradle-git-properties
gradleGitProperties = { id = "com.gorylenko.gradle-git-properties", version.ref = "gradle-git-properties" }

# SonarQube Scanner for Gradle - https://github.com/SonarSource/sonar-scanner-gradle
sonar = { id = "org.sonarqube", version.ref="gradle-sonar" }

# Error-prone plugin - https://github.com/tbroyer/gradle-errorprone-plugin
errorprone = { id ="net.ltgt.errorprone", version.ref = "gradle-errorprone" }

# Gradle Plugin for Node - https://github.com/node-gradle/gradle-node-plugin
node = { id = "com.github.node-gradle.node", version.ref = "gradle-node" }
